FROM node:22-alpine as builder

WORKDIR /app

# Install build tools
RUN apk add --no-cache make gcc g++ python3

COPY package*.json ./
RUN npm install
# Rebuild bcrypt for Alpine 
RUN npm rebuild bcrypt --build-from-source

# Remove build tools to slim down image
RUN apk del make gcc g++ python3

COPY . .
RUN npm run build scheduler-service

FROM node:22-alpine AS production
WORKDIR /app
COPY --from=builder /app/dist/apps/scheduler-service ./dist
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 4000
CMD ["node", "dist/main"]
